function window_pop = createWindowingPopup(parentNode, pos_x, pos_y, callbackFcn)
%CREATEWINDOWINGPOPUP Summary of this function goes here
    window_pop = uicontrol('Parent', parentNode, 'Style', 'popupmenu', ...
        'String', {'Standard', 'FullDynamic', 'Abdomen', ...
        'Angiography', 'Bone', 'Brain', 'Chest', 'Lung'}, ...
        'Position', [pos_x, pos_y, 100, 30], 'Callback', callbackFcn);
end

