function seg_radio = createSegmentationRadio(parentNode, pos_x, pos_y, display, callbackFcn)
%SEGMENTATIONRADIO Summary of this function goes here
    seg_radio  = uicontrol('Parent', parentNode, ...
        'Style', 'radiobutton', ...
        'String', 'Segmentation', ...
        'Position', [pos_x, pos_y, 130, 30],...
        'Visible', display, ...
        'Callback', callbackFcn);
    
end

