function scroll = createScrollbar(parentNode, num_slices, pos_x, pos_y, callbackFcn)
%CREATESCROLLBAR Summary of this function goes here
    scroll = uicontrol('Parent', parentNode, 'Style', 'slider', ...
            'Min', 1, 'Max', num_slices, 'Value', 1, 'SliderStep', ...
            [1/(num_slices-1) 10/(num_slices-1)], ...
            'Position', [pos_x, pos_y, 20, 300], 'Callback', callbackFcn);
end

