function measurement_figure = createMeasurementFigure()
%CREATEMEASUREMENTFIGURE Summary of this function goes here
    start_position = [1400, 100, 320, 768];
    measurement_figure = figure('Name', 'Measurements', ...
        'Position', start_position, ...
        'MenuBar', 'none', ...
        'ToolBar', 'none'...
        );
    set(measurement_figure, 'NumberTitle', 'off');
    set(measurement_figure, 'Resize', 'off');
end

